version: "3.9"
services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres_intranet_docker
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - db-data:/var/lib/postgresql/data\
    networks:
      - apache-php74-postgres-node

  adminer:
    image: adminer
    container_name: adminer_intranet_docker
    restart: always
    ports:
      - 8080:8080
    networks:
      - apache-php74-postgres-node

  www:
    build: php
    container_name: php_intranet_docker
    ports:
      - "8001:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - apache-php74-postgres-node

  nodejs:
    image: node:lts-alpine
    container_name: nodejs_intranet_docker
    volumes:
      - ./:/var/www
    networks:
      - apache-php74-postgres-node

volumes :
  db-data:
networks:
  apache-php74-postgres-node:


